export const ADMIN_IS_SUPERUSER = true;

export const ROLES = {
  WORKER: 'WORKER',
  EMPLOYER: 'EMPLOYER',
  ADMIN: 'ADMIN'
};

export const PERMISSIONS = {
  // Gigs
  GIG_CREATE: 'GIG_CREATE',
  GIG_EDIT_OWN: 'GIG_EDIT_OWN',
  GIG_DELETE_OWN: 'GIG_DELETE_OWN',
  GIG_VIEW_ALL: 'GIG_VIEW_ALL',
  
  //Assignments
  ASSIGNMENT_APPLY: 'ASSIGNMENT_APPLY',
  ASSIGNMENT_VIEW_OWN: 'ASSIGNMENT_VIEW_OWN',
  EVIDENCE_SUBMIT: 'EVIDENCE_SUBMIT',
  EVIDENCE_REVIEW: 'EVIDENCE_REVIEW',

  // Financials
  ESCROW_INITIATE: 'ESCROW_INITIATE',
  ESCROW_RELEASE: 'ESCROW_RELEASE',
  TRANSACTION_VIEW_OWN: 'TRANSACTION_VIEW_OWN',
  TRANSACTION_VIEW_ALL: 'TRANSACTION_VIEW_ALL',

  // Trust & Identity
  PROFILE_EDIT_OWN: 'PROFILE_EDIT_OWN',
  RATING_SUBMIT: 'RATING_SUBMIT',
  TRAINING_TAKE: 'TRAINING_TAKE',

  // Admin Specific
  DISPUTE_RESOLVE: 'DISPUTE_RESOLVE',
  SYSTEM_REPORT_VIEW: 'SYSTEM_REPORT_VIEW',
  USER_SUSPEND: 'USER_SUSPEND'
};

export const ROLE_PERMISSIONS = {
  [ROLES.WORKER]: [
    PERMISSIONS.GIG_VIEW_ALL,
    PERMISSIONS.ASSIGNMENT_APPLY,
    PERMISSIONS.ASSIGNMENT_VIEW_OWN,
    PERMISSIONS.EVIDENCE_SUBMIT,
    PERMISSIONS.TRANSACTION_VIEW_OWN,
    PERMISSIONS.PROFILE_EDIT_OWN,
    PERMISSIONS.RATING_SUBMIT,
    PERMISSIONS.TRAINING_TAKE
  ],
  [ROLES.EMPLOYER]: [
    PERMISSIONS.GIG_CREATE,
    PERMISSIONS.GIG_EDIT_OWN,
    PERMISSIONS.GIG_DELETE_OWN,
    PERMISSIONS.GIG_VIEW_ALL,
    PERMISSIONS.ASSIGNMENT_VIEW_OWN,
    PERMISSIONS.EVIDENCE_REVIEW,
    PERMISSIONS.ESCROW_INITIATE,
    PERMISSIONS.ESCROW_RELEASE,
    PERMISSIONS.TRANSACTION_VIEW_OWN,
    PERMISSIONS.PROFILE_EDIT_OWN,
    PERMISSIONS.RATING_SUBMIT
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.GIG_VIEW_ALL,
    PERMISSIONS.TRANSACTION_VIEW_ALL,
    PERMISSIONS.DISPUTE_RESOLVE,
    PERMISSIONS.SYSTEM_REPORT_VIEW,
    PERMISSIONS.USER_SUSPEND
  ]
};
